### ISSUE TITLE
BookとItemのリレーションをつくる

### ISSUE THREAD

**Issue by kametanir** [kiriharat-bizsys/book-stand#15]
BookとItemモデルのリレーションをつくる
ISBNコードをFKとする？

**Comment by kametanir** [comment]
オブジェクト名称を見直す
書籍のマスタ情報：Book
貸出情報：Rental

**Comment by kametanir** [comment]
参考
https://qiita.com/RyoMa_0923/items/89a490d2bc3fb34f123a
https://qiita.com/t-iguchi/items/e7170d97ecb5b1cff1a2

**Comment by niikurak** [comment]
完了した。
Itemモデル内に。bookという外部キーを設定した。
