### ISSUE TITLE
一覧画面に書籍名を表示する

### ISSUE THREAD

**Issue by kametanir** [kiriharat-bizsys/book-stand#16]
一覧画面の書籍名には、views.pyでItemとBookを結合した情報を変数につめて、その変数から取得した書籍名を表示させる

**Comment by kametanir** [comment]
#15　close後に実施

**Comment by kametanir** [comment]
参考
https://y-hilite.com/3236/

**Comment by niikurak** [comment]
完了しました。
ItemFilterViewのget_context_dataにて、contextにキーと書籍名の辞書を追加。
テンプレートにて辞書の値を表示させた。

**Comment by kametanir** [comment]
Done
