### ISSUE TITLE
提供者の設定値変更

### ISSUE THREAD

**Issue by kiriharat-bizsys** [kiriharat-bizsys/book-stand#2]
提供者の設定値は、画面入力ではなく、userに変更する

**Comment by kiriharat-bizsys** [comment]
下記ブログに書かれている```AUTH_USER_MODEL```を参照してはいかがでしょうか。
https://djangobrothers.com/blogs/referencing_the_user_model/

**Comment by kiriharat-bizsys** [comment]
現状ユーザー名がそのままDBに格納＆画面に表示されるため、要改善
※ユーザー名はログイン時に入力するため「kametanir」などのローマ字が好ましいが、現状は「亀谷理恵」と入力する実装となっている。

**Comment by kiriharat-bizsys** [comment]
提供者、貸出者のプルダウンのchoiceをfast_nameに修正することでログインIDと表示名を正しくする

**Comment by kametanir** [comment]
ユーザー登録時に登録する値、各項目の期待値を整理したい

**Comment by kiriharat-bizsys** [comment]
Done
choiceをfull_nameに修正したため、
ログインIDはkametanir、画面表示名は亀谷理恵となった
