### ISSUE TITLE
貸出ステータスの更新条件追加

### ISSUE THREAD

**Issue by kiriharat-bizsys** [kiriharat-bizsys/book-stand#3]
貸出を行いたい場合　
　貸出ステータス＝貸出中は貸出ステータス＝貸出可能の場合のみ更新可能
返却を行いたい場合
　貸出ステータス＝貸出可能は、貸出者かつ貸出ステータス＝貸出可能の場合のみ更新可能
提供終了したい場合
　貸出ステータス=貸出可能　かつ　提供者のみ更新可能

**Comment by kiriharat-bizsys** [comment]
request.POSTの値を取得する
https://tokkan.net/python/django2.html

**Comment by kiriharat-bizsys** [comment]
ステータスの前後を見るのは難しくないかい。

**Comment by kametanir** [comment]
変更前のステータスをURLのクエリパラメータから取得したい

**Comment by kiriharat-bizsys** [comment]
エラーのときにメッセージを同じ画面に返す
https://docs.djangoproject.com/ja/2.2/intro/tutorial03/

**Comment by kametanir** [comment]
エラー時は、更新または詳細画面に遷移し、画面上にエラーメッセージを表示する対応としたいが、更新または詳細画面にリダイレクトするには、URLのクエリパラメーターにpk（id）をセットする必要がある

**Comment by kiriharat-bizsys** [comment]
Done
