### ISSUE TITLE
提供者／貸出者のModels.pyのデフォルト値変更

### ISSUE THREAD

**Issue by kametanir** [kiriharat-bizsys/book-stand#7]
1. 提供者／貸出者のModels.pyのデフォルト値が”admin”になっているのでログインユーザーに変更する
2. 提供者／貸出者を編集不可項目に変更する

**Comment by kiriharat-bizsys** [comment]
提供者は編集不可項目への変更と登録処理にログインユーザーを提供者へ設定する処理を追加

**Comment by kiriharat-bizsys** [comment]
Done
